GOOGLE_API_KEY = "AIzaSyDrCgz1QdzYdm5TNbpBXjTf9Y7Uy0BybfI"
  
[qdrant]
url = "https://647615bf-9468-4f8e-9c22-66f7929e14f3.europe-west3-0.gcp.cloud.qdrant.io:6333"
api_key="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.d34m2ZcvzmfKPl3H2z9ge_Oy4Yc3v4PuhLbUeJ_XHgk"


